#[derive(Debug, serde::Deserialize)]
pub struct Record {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "category")]
    pub category: Option<String>,
    #[serde(rename = "id1")]
    pub identifier1: Option<String>,
    #[serde(rename = "pw1")]
    pub password1: Option<String>,
    #[serde(rename = "id2")]
    pub identifier2: Option<String>,
    #[serde(rename = "pw2")]
    pub password2: Option<String>,
    #[serde(rename = "id3")]
    pub identifier3: Option<String>,
    #[serde(rename = "pw3")]
    pub password3: Option<String>,
    #[serde(rename = "id4")]
    pub identifier4: Option<String>,
    #[serde(rename = "pw4")]
    pub password4: Option<String>,
    #[serde(rename = "id5")]
    pub identifier5: Option<String>,
    #[serde(rename = "pw5")]
    pub password5: Option<String>,
    #[serde(rename = "URL1")]
    pub url1: Option<String>,
    #[serde(rename = "URL2")]
    pub url2: Option<String>,
    #[serde(rename = "URL3")]
    pub url3: Option<String>,
    #[serde(rename = "URL4")]
    pub url4: Option<String>,
    #[serde(rename = "URL5")]
    pub url5: Option<String>,
    #[serde(rename = "remarks")]
    pub remarks: Option<String>,
}
